name: Simple Docker Build

on:
  push:
    branches: [ main ]

env:
  DOCKER_REGISTRY: docker.io
  DOCKER_REPOSITORY:  ${{ secrets.DOCKERHUB_USERNAME }}/gemini-cli

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_REPOSITORY }}:latest
          ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_REPOSITORY }}:${{ github.sha }}
        build-args: |
          GEMINI_CLI_VERSION=0.14
          SANDBOX_NAME=gemini-cli-sandbox
        cache-from: type=gha
        cache-to: type=gha,mode=max